name: 🐞 Problem Report
description: Report bugs or issues
title: "[Problem]: "
labels: ["problem"]

body:
  - type: markdown
    attributes:
      value: |
        Before creating a report, please read the [Wiki](https://github.com/be-bub/genderbub/wiki).

  - type: dropdown
    id: version
    attributes:
      label: Minecraft Version
      options:
        - 1.20.1
        - 1.21.1
    validations:
      required: true

  - type: textarea
    id: description
    attributes:
      label: Problem description
    validations:
      required: true
